In [13]:
import numpy as np
import pandas as pd

rawp = "data/raw/"
cleanp = "data/clean/"
filname = "exemplo1.csv"

def get_df(num_users:int = 1000, num_products:int = 100):
    users = [i for i in range(num_users)]
    products = [i for i in range(num_products)]
    return pd.DataFrame(index=users, columns=products, dtype="float64")

def get_clustersizes(datasize: int =1000, num_cl: int = 5):
    n_cl = 0
    while n_cl  != num_cl: 
        start = 0
        clustersizes = [0]
        while start < datasize:
            size = np.random.randint(datasize)
            if start + size >= datasize:
                clustersizes.append(datasize)
                break
            start += size
            clustersizes.append(start)
        n_cl = len(clustersizes)-1
    return clustersizes

def get_cluster_products(num_products:int = 100, num_clusters: int = 6, bundle_size_max: int = 5):
    cl = pd.DataFrame(columns=[i for i in range(num_products)], index=[i for i in range(num_clusters)], dtype="Int64" )
    for i in range(num_clusters):
        sz = np.random.randint(1, bundle_size_max)
        idx_products = np.random.randint(num_products, size = sz)
        cl.iloc[i, idx_products] = 1
        print(idx_products)
    return cl.fillna(0)

def generate_df(num_users: int = 1000, num_products:int = 100, max: int = 200, bundle_size: int = 5, noise_ratio: float = 0.1, num_clusters: int = 5):
    df = get_df(num_users, num_products)
    csizes = get_clustersizes(num_users, num_clusters)
    print(csizes)
    cp = get_cluster_products(num_products, len(csizes)-1, bundle_size)
    for i in range(len(csizes)-1):
        df.iloc[[j for j in range(csizes[i], csizes[i+1])]] = cp.iloc[i]
    for i in range(num_users):
        df.iloc[i]
        max_user = np.random.randint(max//3, max, size=num_products)
        user_inoise = np.random.randint(1 + np.floor(max_user*noise_ratio), size=num_products)*np.absolute(np.random.normal(0,1, num_products))
        #print(max_user)
        df.iloc[i] =  max_user*df.iloc[i] + user_inoise
        df.iloc[i] = np.floor(df.iloc[i])
    return df
    



In [15]:
noise = 0.1
generate_df(500, 100, 200, 10, noise, 8).to_csv(rawp+filname)
#logpath = f"data/log_{filname}.txt"
#log = open(logpath, "a", encoding="utf-8")
#log.write(f"noise = {noise} \n",)



[0, 9, 27, 35, 116, 234, 269, 313, 500]
[44 13 23  5 50]
[ 1  6 43 25]
[33 86 15 44 95 47 91 31 84]
[80 93 24 54 19 71 96 76 85]
[35]
[86 27 55 61 89 67 89]
[51 96 89 55]
[27 41]
